#!/usr/bin/env python
import argparse
import os

import numpy as np
from QSAR_Lab.Space_Tools.Align_two_3D_object import (AA_add_transpose,
                                                      NM_translate)

parser = argparse.ArgumentParser(
    description="""
    Create XYZ files build from 2 structures (s1, s2). Automatically rotate and translate objects to each other (rotation matrix from 
    quaternions). Program can be use with flag -all then you direct list with structures 1 (s1) and list with structures 2 (s2) - automatically 
    create main directories -> sub_directories (by structures 1) -> sub_sub_directories (by structures 2).

    Dodaje do struktury roznie zorientowane dipole elektryczne.
    """,
    epilog="""Example: --> ./make_XYZ.py -s1 dir1/*.xyz -s2 dir2/*.xyz -all,  
    --> ./make_XYZ.py -s1 s1.xyz -s2 s2.xyz""",
)
parser.add_argument(
    "-s1",
    nargs="+",
    help="structures 1 - can be either only one specific structures or path to structures",
)
parser.add_argument(
    "-s2",
    nargs="+",
    help="structures 2 - can be either only one specific structures or path to structures",
)
parser.add_argument(
    "-all",
    action="store_true",
    help="""if active; its work on lists of structures and automatically create directories with sub_directories if not; 
    its based on one structers 1 and one structures 2 then printing""",
)

options = parser.parse_args()

if options.all:

    def to_xyz(data):
        data = np.array(["{:.5f}".format(line) for line in data.flatten()]).reshape(
            data.shape
        )
        return data

    def save(xyz, path):
        with open(os.path.join(dir, sub_dir1, path), "w") as f:
            f.write(str(len(xyz)) + "\n")
            f.write("XYZ file generated by Script\n")
            for coor, n in zip(xyz, name):
                f.write("{}{:>20}{:>13}{:>13}\n".format(n, coor[0], coor[1], coor[2]))
        return 1

    def atom_info(xyz1, xyz2, kind):
        with open(os.path.join(dir, sub_dir1, f"atom_info_{kind}"), "w") as f:
            f.write(sub_dir1 + f"=1-{len(xyz1)}\n")
            f.write(sub_dir2 + f"={1+len(xyz1)}-{len(xyz2)}\n")
        return 1

    dir = input("Wrpowadz nazwe katalogu lub wcisnij ENTER: ")

    if dir == "":
        dir = "New_XYZ_structers"

    path = str()

    if not os.path.isdir(dir):
        os.mkdir(dir)

    for i in options.s1:
        for j in options.s2:
            obj1 = NM_translate(i)
            xyz_obj1 = obj1.translate_center_to_zero

            obj2 = AA_add_transpose(i, j)
            xyz_obj2 = obj2.rotate_2D_object
            name = np.append(obj1.get_name, obj2.get_name)

            xyz_rotated = np.append(xyz_obj1, xyz_obj2[0], axis=0).round(decimals=4)
            xyz_horizontal = np.append(xyz_obj1, xyz_obj2[1], axis=0).round(decimals=4)
            xyz_vertical = np.append(xyz_obj1, xyz_obj2[2], axis=0).round(decimals=4)

            xyz_rotated = to_xyz(xyz_rotated)
            xyz_horizontal = to_xyz(xyz_horizontal)
            xyz_vertical = to_xyz(xyz_vertical)

            sub_dir1 = i.split("/")[-1].replace(".xyz", "")
            if not os.path.isdir(os.path.join(dir, sub_dir1)):
                os.mkdir(os.path.join(dir, sub_dir1))
            sub_dir2 = j.split("/")[-1].replace(".xyz", "")

            if "/" in i or j:
                path = i.split("/")[-1].replace(".xyz", "") + "_" + j.split("/")[-1]

            path_rotated = path.replace(".xyz", "_rotated.xyz")
            path_horizontal = path.replace(".xyz", "_horizontal.xyz")
            path_vertcial = path.replace(".xyz", "_vertcial.xyz")

            save(xyz_rotated, path_rotated)
            save(xyz_horizontal, path_horizontal)
            save(xyz_vertical, path_vertcial)

            atom_info(xyz_obj1, xyz_rotated, "rotated")
            atom_info(xyz_obj1, xyz_horizontal, "horizontal")
            atom_info(xyz_obj1, xyz_vertical, "vertical")
else:
    try:
        fname1 = options.s1[0]
        fname2 = options.s2[0]
    except:
        print("Can't find an argument (Gaussian log file).")
    else:
        obj1 = NM_translate(fname1)
        xyz_obj1 = obj1.translate_center_to_zero

        obj2 = AA_add_transpose(fname1, fname2)
        xyz_obj2 = obj2.rotate_2D_object
        name = np.append(obj1.get_name, obj2.get_name)

        xyz_rotated = np.append(xyz_obj1, xyz_obj2[0], axis=0).round(decimals=4)
        # mozna dopisac funkcjonalnosc zeby tez wyswietlane byly pozostale xyz
        xyz_horizontal = np.append(xyz_obj1, xyz_obj2[1], axis=0).round(decimals=4)
        xyz_vertical = np.append(xyz_obj1, xyz_obj2[2], axis=0).round(decimals=4)

        xyz_rotated = np.array(
            ["{:.5f}".format(line) for line in xyz_rotated.flatten()]
        ).reshape(xyz_rotated.shape)

        print(str(len(xyz_rotated)))
        print("XYZ file generated by Script")
        for coor, n in zip(xyz_rotated, name):
            print("{}{:>20}{:>13}{:>13}".format(n, coor[0], coor[1], coor[2]))
