#!/bin/awk -f
BEGIN {
    nm2A = 10.0;
    tinkertitfmt = "%1d\n Generated by Script\n";
    tinkerofmt = "%3s %17.6f %16.6f %16.6f\n";
    tinkerhfmt = "%4s %16.6f %16.6f %16.6f\n";
    tinkerxfmt = "%3s %17.6f %16.6f %16.6f\n";

# atom types for AMOEBA09 ff
    printf("Auto-generated TINKER XYZ file - remember to check atom types and connectivity for your molecules!\n") > "/dev/stderr";
}
{
    if (FNR == 1) {
        title = $0;
    } else if (FNR == 2) {
        atoms = $1;
        printf(tinkertitfmt, atoms, title);
    } else {
        resname = substr($0, 6, 3);
# first print other molecules
        if (resname != "SOL" && $2 !~ /[0-9][.]/) {
            atmname = $2;
            atmnum = $3;
            printf(tinkerxfmt, atmname, $4 * nm2A, $5 * nm2A, $6 * nm2A);
# next print solvent
        } else {
            atmname = substr($2, 1, 1);
            atmnum = $3;
            if (atmname  == "O") {
                onum = atmnum;
                printf(tinkerofmt, atmname, $4 * nm2A, $5 * nm2A, $6 * nm2A);
            } else if (atmname == "H") {
            # } else if ("H" in atmname) {
                printf(tinkerhfmt, $2, $4 * nm2A, $5 * nm2A, $6 * nm2A);
            }
        }
    }
}
